const GET_TODOS_BEGIN = 'GET_TODOS_BEGIN';
const GET_TODOS_SUCCESS = 'GET_TODOS_SUCCESS';
const GET_TODOS_ERROR = 'GET_TODOS_ERROR';
const HANDLE_CHANGE = 'HANDLE_CHANGE';
const CREATE_TODO = 'CREATE_TODO';
const DELETE_TODO = 'DELETE_TODO';
const CLEAR_TODOS = 'CLEAR_TODOS';
const EDIT_TODO = 'EDIT_TODO';
const UPDATE_TODO = 'UPDATE_TODO';
const BACK_TO_DEFAULT = 'BACK_TO_DEFAULT';

export {
  GET_TODOS_BEGIN,
  GET_TODOS_SUCCESS,
  GET_TODOS_ERROR,
  HANDLE_CHANGE,
  CREATE_TODO,
  DELETE_TODO,
  CLEAR_TODOS,
  EDIT_TODO,
  UPDATE_TODO,
  BACK_TO_DEFAULT
};
